### ISSUE TITLE
Ball bouncing

### ISSUE THREAD

**Issue by SageAndromeda** [darienyoder/software-engineering-team-beta#27]
The ball doesn't bounce off the walls on a proper trajectory. It needs to go out on the same angle it came in.
Ex: Ball hits wall at 45 degree angle and bounces at 45 degree angle.
Ex: Ball hits wall at 20 degree angle, it leaves at 20 degree angle

**Comment by clickyquack** [comment]
I think I fixed this, you can see it here: https://github.com/darienyoder/software-engineering-team-beta/tree/kai.
Also new problem with the windmill now being able to push it out of bounds when it couldn't before has arisen but that should be relatively easy to fix when I get the chance.

**Comment by clickyquack** [comment]
I know exactly how to implement this in theory (see here: https://math.stackexchange.com/questions/13261/how-to-get-a-reflection-vector)
But I need to be able to run a block of code whenever the ball collides with a given wall in such a way that I can access the attributes of the wall that it collides with. Due to my own lack of experience with JS/p5/p5play, I wasn't able to figure out how to do this on my own (I've tried, trust me). Solutions that I expected to work did not work for reasons beyond my understanding. So I'm asking for help, and if anyone else can set up an if statement that lets me do this then I can finish the rest.

**Comment by darienyoder** [comment]
This might have a syntax error or two, but the formula for getting the normal vector should look something like this. The [p5 Vector class](https://p5js.org/reference/p5/p5.Vector/) has a few methods that may be useful for calculating reflections.
``` JavaScript
// Iterate through each wall in the level
for (var wall of level.walls)
{
    // Check if the ball and the wall have collided
    if (ball.collides(wall))
    {
        let normalVector;

        // If the wall is a circle (like on rounded corners), the normal is the direction from the wall to the ball
        if (wall.width == wall.height)
        {
            normalVector = createVector(ball.x, ball.y).sub(createVector(wall.x, wall.y)).normalized();
        }
        // If the wall is a segment, the normal is the rotation of the sprite +/- 90 degrees
        // There is a normal vector for each side of the wall, so calculate each vector's distance to the ball and use whichever is closest
        else
        {
            let positiveNormalVector = p5.Vector.fromAngle(wall.rotation + 90);
            let negativeNormalVector = p5.Vector.fromAngle(wall.rotation - 90);

            if (ball.distanceTo(createVector(wall.x, wall.y) + positiveNormalVector) < ball.distanceTo(createVector(wall.x, wall.y) + negativeNormalVector))
            {
                normalVector = positiveNormalVector;
            }
            else
            {
                normalVector = negativeNormalVector;
            }
        }

        //
        // Code for calculating new velocity goes here
        //

        break;
    }
}
```

**Comment by clickyquack** [comment]
I've implemented it here: https://github.com/darienyoder/software-engineering-team-beta/tree/ball-bouncing. I've debugged it and it calculates the new velocity given the wall it hits and the old velocity just find. However, a new problem has arisen. I believe what's happening is it tries to apply the default physics first, then apply the new bouncing physics on top of that. I'm not sure how to set this up such that it completely overwrites the default p5play collision physics (while still checking for collision instead of overlapping). But I was able to prove that this is (probably) what's happening by removing wall collision, and checking when the wall overlaps the ball instead of collides it. The branch https://github.com/darienyoder/software-engineering-team-beta/tree/ball-bouncing-alt has this, and the ball bounces exactly as I intend it to. But because it uses the overlaps function instead of the collides function, the windmill is able to push it out of bounds.
